import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "../globals.css";
import NavigationBar from "@/lib/uiComponents/navigation/NavigationBar";
import React from "react";
import Aos from "@/lib/utils/aos";
import ProductsStore from "@/lib/stores/ProductsStore";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "KickRocks",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Aos/>
        <ProductsStore>
            <NavigationBar/>
            {children}
        </ProductsStore>
        </body>
        </html>
    );
}
